### ISSUE TITLE
error on snmp

### ISSUE THREAD

**Issue by fromanm1** [rayholtz/PublicRepo#1]
Im using a tipplite smartin 3000vs

snmp works fine. but when I run the script I get this.

 perl  check_tlups_battstatus.pl  -H MY_IP -C public
ERROR: netsnmp : Received noSuchName(2) error-status at error-index 1.

also the oid aims to .1.3.6.1.4.1.850.1.1.3.1.3.1.1.1.1.1 but it doesn't exist.
I guess the right one is .1.3.6.1.4.1.850.10.2.3.2.1.5.1 (from snmpwalk)

**Comment by rayholtz** [comment]
I'm sorry its not working for you, but thank you for trying it out.
You might need to change the oid depending on your specific version of UPS/webcard.  This is what worked for me in my environment then.  Unfortunately, I don't have access to Nagios or TrippLite UPSes anymore since I changed jobs, so I can't test this.  

The error might be because of the difference in oid.  Try to change the OID within the perl code, and see if that helps you.
